## Numpy


In [1]:
#Numpy
import numpy as np


In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
arr = np.array(lista)
type(arr)

numpy.ndarray

In [7]:
#Objetos de múltiples dimensiones
#Matrices

matriz = np.array([[1,2,3],[4,5,6],[7,8,9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
#Indexado

#Los índices inician de 0
#Accedemos al primer valor del array
arr[0]

1

In [12]:
#Indexado con matrices

#Muestra la primera fila
matriz[0]

#Para ir a una fila y columna
matriz[0,2]


3

In [14]:
# Para acceder a más de un objeto
#Los tres primeros valores
#Slicing

#Funciona con un start y un end
arr[0:3]
#Si no se le da valor, inicia de 0 arr[:3]
#Si no se le da un final, toma de un valor hasta el final arr[3:]
#Si se no se le da ningún valor y se quiere de tres en tres
arr[::3]
#Si se le da -1 empieza desde el final

array([1, 4, 7])

In [16]:
#Slicing en matrices
#De igual maneras, separados por coma ","
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

## Tipos de datos

In [18]:
 arr = np.array([1,2,3])
    
#Para saber que tipo de valores tiene nuestro array
arr.dtype

dtype('int64')

In [19]:
# Para indicarle que tipo de valores queremos que tenga

arr = np.array([1,2,3,4], dtype='float64')
arr.dtype

dtype('float64')

In [20]:
#Para cambiar el tipo de datos
arr = arr.astype(np.float64)

In [21]:
arr = np.array([0,1,2,3,4])
arr = arr.astype(np.bool_)
arr
#Los ceros serán siempre en falso y el resto será verdadero.

array([False,  True,  True,  True,  True])

In [22]:
#Voler de tipo str a int

arr = np.array(['0','1','2','3','4'])
arr = arr.astype(np.int8)
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [5]:
#Dimensiones

scalar = np.array(42)
print(scalar)
scalar.ndim

42


0

In [6]:
vector = np.array([1,2,3])
print(vector)
vector.ndim

[1 2 3]


1

In [7]:
matriz = np.array([[1,2,3],[4,5,6]])
print(matriz)
matriz.ndim

[[1 2 3]
 [4 5 6]]


2

In [9]:
matriz = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(matriz)
matriz.ndim

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


3

In [11]:
#Agregar o quitar dimensiones

vector = np.array([1,2,3], ndmin = 10)
print(vector)
vector.ndim

[[[[[[[[[[1 2 3]]]]]]]]]]


10

In [12]:
expand = np.expand_dims(np.array([1,2,3]), axis=0)
print(expand)
expand.ndim

[[1 2 3]]


2

In [13]:
print(vector, vector.ndim)
vector_2 = np.squeeze(vector)
print(vector_2, vector_2.ndim)

[[[[[[[[[[1 2 3]]]]]]]]]] 10
[1 2 3] 1


## Creando arrays
NumPy nos da varios métodos muy eficientes para crear arrays desde 0. Este método de NumPy nos permite generar arrays sin definir previamente una lista

In [2]:
#Código basado en python, no numpy
#no es un array.
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [6]:
#con numpy
#Llena un array de un valor a otro
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
#Tiene dato inicial, dato stop y dato de salto
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [8]:
#Se puede llenar un array con ceros
np.zeros(3)

array([0., 0., 0.])

La utilidad de definir arrays con ceros se utiliza para crear un esquema previo.

In [9]:
#Definir un array de tipo matricial de 10x10

np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [10]:
#Si se quiere llenar con unos, se utiliza ones

np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [12]:
#Otro interesante es linspace
#Tiene un valor inicio, uno final, y cuántos números quiero generar y realiza una distribución
#basado en lo que se le dicte
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [15]:
#Genera una lista normalizada
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [16]:
#Función eye es la función identidad
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#Para generar valores aleatorios
#Entre 0 y 1
np.random.rand()

0.5155594575257174

In [21]:
# Un array con 4 valores aleatorios
np.random.rand(4)

array([0.39469402, 0.23586341, 0.77346236, 0.33793411])

In [22]:
#Una matrix de 4x3 con valores aleatorios
np.random.rand(4,3)

array([[0.75062323, 0.10354209, 0.06742506],
       [0.12859531, 0.74786242, 0.31811597],
       [0.01500981, 0.52758304, 0.11150227],
       [0.54302906, 0.3419203 , 0.27921534]])

In [25]:
#Para generar números aleatorios enteros entre 1 y 15
np.random.randint(1,15)

13

In [26]:
# Si se quiere en una estructura

np.random.randint(1,100,(5,5))

array([[95, 25, 89, 41, 55],
       [27, 79, 67, 14, 45],
       [30,  6, 87, 46, 25],
       [16,  2, 68, 30, 94],
       [ 1, 19, 41, 78, 19]])

## Shape y Reshape

Hay dos funciones muy importantes de los arreglos, shape y reshape. La forma de un arreglo nos va a decir con que estructura se está trabajando. 

In [28]:
#generamos un array

arr = np.random.randint(1,10,(3,2))

In [30]:
#Para saber la forma de la matrix
#filas por columnas
arr.shape

(3, 2)

In [31]:
#si quiero cambiar la forma de un array
arr.reshape(1,6)

array([[8, 2, 9, 9, 7, 2]])

In [32]:
arr.reshape(2,3)

array([[8, 2, 9],
       [9, 7, 2]])

In [33]:
#Otra forma de escribirlo
np.reshape(arr,(1,6))

array([[8, 2, 9, 9, 7, 2]])

In [34]:
#en la forma de c
np.reshape(arr,(2,3),'C')

array([[8, 2, 9],
       [9, 7, 2]])

In [35]:
#En lenguaje de Fortran
np.reshape(arr,(2,3),'F')

array([[8, 7, 9],
       [9, 2, 2]])

In [36]:
#Como está guardado en mi memoria, mejor optimizado
np.reshape(arr,(2,3),'A')

array([[8, 2, 9],
       [9, 7, 2]])

## Funciones principales de NumPy

vamos a ver cuáles son las funciones que se utilizan normalmente con NumPy cuando analizamos los datos.

In [39]:
arr = np.random.randint(1,20,10)
matriz = arr.reshape(2,5)
matriz

array([[19, 13, 15, 13, 12],
       [ 7,  6,  9, 10, 15]])

In [40]:
#La función max se trae el número más grande dentro del array

arr.max()

19

In [41]:
matriz.max()

19

In [43]:
#Si quiero que lo haga solo del eje 1
matriz.max(0)

array([19, 13, 15, 13, 15])

In [44]:
#Con argmax nos da el índice donde se encuentra nuestro valor mayor
matriz.argmax()

0

In [45]:
#Y también se le puede indicar en que índice
matriz.argmax(0)

array([0, 0, 0, 0, 1])

In [46]:
#Para encontrar el valor minimo
matriz.min()

6

In [47]:
#También existe el argmin
matriz.argmin()

6

In [48]:
#Y se le puede indicar los índices
matriz.argmin(0)

array([1, 1, 1, 1, 0])

In [49]:
#Pick to Pick
arr

array([19, 13, 15, 13, 12,  7,  6,  9, 10, 15])

In [51]:
#De 6 a 19 hay una diferencia de 13
arr.ptp()

13

In [52]:
#Para hacerlo en algún índice
matriz.ptp(0)

array([12,  7,  6,  3,  3])

In [60]:
#Percentile especifica el percentil que se está trabajando
#La mediana
np.percentile(arr,50)

12.5

In [61]:
#Con sort ordena de menor a mayor los números del arreglo

arr.sort()
arr

array([ 6,  7,  9, 10, 12, 13, 13, 15, 15, 19])

In [62]:
#Con median se encuentra la mediana (percentil 50)
np.median(arr)

12.5

In [63]:
#Para matrices
np.median(matriz,0)

array([ 9.5, 10. , 12. , 12.5, 15.5])

In [64]:
#Para la desviación estandar
np.std(arr)

3.7802116342871597

In [65]:
#La varianza
np.var(arr)

14.289999999999997

In [66]:
#La desviación estandar al cuadrado es la varianza
np.std(arr)**2

14.29

In [67]:
#La media, distinto a la mediana
np.mean(arr)

11.9

In [83]:
#La concatenación}

a = np.array([[1,2],[3,4]])
b = np.array([5,6])

#np.concatenate((a,b),axis=0)

In [84]:
b = np.expand_dims(b,axis=0)

In [85]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [87]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

## Copy

.copy() nos permite copiar un array de NumPy en otras variables de tal forma que al modificar el nuevo array los cambios no se vean refejados en array original

In [95]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
trozo_de_arr = arr[0:6]
trozo_de_arr

array([0, 1, 2, 3, 4, 5])

In [99]:
trozo_de_arr[:] = 0
trozo_de_arr

array([0, 0, 0, 0, 0, 0])

In [100]:
#También modifica al array original
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

In [101]:
arr_copy = arr.copy()
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [102]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

## Condiciones
Las condiciones nos permiten hacer consultas más específicas

In [104]:
arr = np.linspace(1,10,10, dtype = 'int8')
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [105]:
#Para obtener los números mayores a 5, regresa una lista booleana
arr > 5 

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [107]:
indices_cond = arr > 5

In [109]:
#Para filtrar los datos
arr[indices_cond]

array([ 6,  7,  8,  9, 10], dtype=int8)

In [110]:
#Con el valor & podemos agregar una condición más
arr[(arr > 5 ) & (arr < 9)]

array([6, 7, 8], dtype=int8)

In [112]:
arr[(arr > 5 )] = 99
arr

array([ 1,  2,  3,  4,  5, 99, 99, 99, 99, 99], dtype=int8)

In [113]:
arr[(arr == 99)]

array([99, 99, 99, 99, 99], dtype=int8)

## Operaciones
Existen diferentes operaciones que se pueden usar con los arrays de NumPy

In [114]:
lista = [1,2]
lista

[1, 2]

In [115]:
#Para multiplicar por dos la lista
lista*2

[1, 2, 1, 2]

In [121]:
#Con NumPy
arr = np.arange(0,10)
arr2 = arr.copy()
#Diferentes a las listas
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [123]:
#suma
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [124]:
#Cuadrado
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [126]:
#Suma vectorial
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [128]:
#operación con matrices
matriz = arr.reshape(2,5)
matriz2 = matriz.copy()

In [130]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [131]:
#suma de matrices
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

In [133]:
#Producto punto de dos matrices

np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [135]:
np.cos(np.pi)

-1.0

## Pandas

In [2]:
import pandas as pd

In [138]:
#Si no se le da un valor al index inicia una lista ordenada empezando de 0
psg_players = pd.Series(['Navas', 'Mbappe','Neymar','Messi'],
         index = [1,7,10,30]
         )

In [141]:
#Con diccionarios

#Podemos ingresarlo en pandas series
dic = {1: 'Navas', 7: 'Mbappe', 10: 'Neymar', 30: 'Messi'}
pd.Series(dic)

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [143]:
#Se entra por el índice
psg_players[1]

'Navas'

In [1]:
my_dic = {'Jugador':['Navas','Mbeppe','Neymar','Messo'],
'Altura':[183.0,170.0,170.0,165.0],
'Goles': [2,200,200,200]
}

In [5]:
df_Players = pd.DataFrame(my_dic,index = [1,7,10,30])

In [6]:
df_Players.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [9]:
df_Players.index

Int64Index([1, 7, 10, 30], dtype='int64')

In [10]:
df_Players

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbeppe   170.0    200
10  Neymar   170.0    200
30   Messo   165.0    200

## Leer archivos CSV y JSON con Pandas

In [11]:
pd.read_csv('/home/jeffersonrl/Descargas/example.csv')

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [12]:
#Si el archivo no viene separado por comas se utiliza pep

pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',')

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [14]:
#Muchos datos no traen un header, por lo que si tiene header se remarca

df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0)

#si no tiene header se indica header = None

In [15]:
df_books.columns


Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [16]:
#Si quiero cambiar los nombres de los encabezados
df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0,
                     names= ['Nombre', 'Autor', 'Rating', 'Reviews', 'Precio', 'Anio', 'Genero'])
df_books

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  Rating  Reviews  Precio  Anio       Genero  
0                    JJ Smith     4.7    17350       8  2016  Non Fiction  
1                Stephen King     4.6     2052      22  2011      Fiction  
2          Jordan B. Peterson     4.7    18979      15  2018  Non Fiction  
3               George Orwell     4.7    21424       6  2017      Fiction  
4    National Geographic Kids     4.8     7665      12  2019  Non Fiction  
..                        ...     ...      ...     ...   ...          ...  
545               Jeff Kinney     4.9     9413       8  2019      Fiction  
546               Jen Sincero     4.7    14331       8  2016  Non Fiction  
547               Jen Sincero     4.7    14331       8  2017  Non Fiction  
548               Jen Sincero     4.7    14331       8  2018  Non Fiction  
549               Jen Sincero     4.7    14331       8  2019  Non Fiction  

[550 rows x 7 columns]

In [17]:
pd.read_json('/home/jeffersonrl/Descargas/jeison.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

In [18]:
#si queremos cambiar el tipo de visualización a pd series

pd.read_json('/home/jeffersonrl/Descargas/jeison.json', typ='Series')

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [19]:
#También se puede llamar archivos de la web si se tiene su url
url = "https://static.platzi.com/media/public/uploads/hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json"

pd.read_json(url)

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

## Filtrado con loc e iloc

In [21]:
#Para hacer un slicing como NumPy
df_books[0:4]

Nombre               Autor  Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith     4.7   
1                        11/22/63: A Novel        Stephen King     4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson     4.7   
3                   1984 (Signet Classics)       George Orwell     4.7   

   Reviews  Precio  Anio       Genero  
0    17350       8  2016  Non Fiction  
1     2052      22  2011      Fiction  
2    18979      15  2018  Non Fiction  
3    21424       6  2017      Fiction

In [22]:
#Si se quiere filtrar por nombres
df_books['Nombre']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Nombre, Length: 550, dtype: object

In [23]:
#Si se quiere por dos columnas, será necesario utilizarlo en una lista de lista
#Con esta misma estructura se podría agregar año
df_books[['Nombre','Autor']]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  
0                    JJ Smith  
1                Stephen King  
2          Jordan B. Peterson  
3               George Orwell  
4    National Geographic Kids  
..                        ...  
545               Jeff Kinney  
546               Jen Sincero  
547               Jen Sincero  
548               Jen Sincero  
549               Jen Sincero  

[550 rows x 2 columns]

In [24]:
#Para filtrar por label

df_books.loc[:]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  Rating  Reviews  Precio  Anio       Genero  
0                    JJ Smith     4.7    17350       8  2016  Non Fiction  
1                Stephen King     4.6     2052      22  2011      Fiction  
2          Jordan B. Peterson     4.7    18979      15  2018  Non Fiction  
3               George Orwell     4.7    21424       6  2017      Fiction  
4    National Geographic Kids     4.8     7665      12  2019  Non Fiction  
..                        ...     ...      ...     ...   ...          ...  
545               Jeff Kinney     4.9     9413       8  2019      Fiction  
546               Jen Sincero     4.7    14331       8  2016  Non Fiction  
547               Jen Sincero     4.7    14331       8  2017  Non Fiction  
548               Jen Sincero     4.7    14331       8  2018  Non Fiction  
549               Jen Sincero     4.7    14331       8  2019  Non Fiction  

[550 rows x 7 columns]

In [25]:
#es diferente porque aquí incluye el último valor
df_books.loc[0:4]

Nombre  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                      Autor  Rating  Reviews  Precio  Anio       Genero  
0                  JJ Smith     4.7    17350       8  2016  Non Fiction  
1              Stephen King     4.6     2052      22  2011      Fiction  
2        Jordan B. Peterson     4.7    18979      15  2018  Non Fiction  
3             George Orwell     4.7    21424       6  2017      Fiction  
4  National Geographic Kids     4.8     7665      12  2019  Non Fiction

In [27]:
#Es mucho mejor para realizar querys
df_books.loc[0:4,['Nombre','Autor']]

Nombre                     Autor
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

In [28]:
#Para una columna de tipo numérico
df_books.loc[:,['Reviews']]

Reviews
0      17350
1       2052
2      18979
3      21424
4       7665
..       ...
545     9413
546    14331
547    14331
548    14331
549    14331

[550 rows x 1 columns]

In [30]:
#Pueden ser operados
df_books.loc[:,['Reviews']]*-1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [31]:
#También con los strings
df_books.loc[:,['Autor']] == 'JJ Smith'

Autor
0     True
1    False
2    False
3    False
4    False
..     ...
545  False
546  False
547  False
548  False
549  False

[550 rows x 1 columns]

In [33]:
#Con iloc se filtra mediante índices.
df_books.iloc[:]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  Rating  Reviews  Precio  Anio       Genero  
0                    JJ Smith     4.7    17350       8  2016  Non Fiction  
1                Stephen King     4.6     2052      22  2011      Fiction  
2          Jordan B. Peterson     4.7    18979      15  2018  Non Fiction  
3               George Orwell     4.7    21424       6  2017      Fiction  
4    National Geographic Kids     4.8     7665      12  2019  Non Fiction  
..                        ...     ...      ...     ...   ...          ...  
545               Jeff Kinney     4.9     9413       8  2019      Fiction  
546               Jen Sincero     4.7    14331       8  2016  Non Fiction  
547               Jen Sincero     4.7    14331       8  2017  Non Fiction  
548               Jen Sincero     4.7    14331       8  2018  Non Fiction  
549               Jen Sincero     4.7    14331       8  2019  Non Fiction  

[550 rows x 7 columns]

In [34]:
#iloc es lo mismo que loc pero la búsqueda será por índice
#trae todo desde 0 hasta el índice 3 (Rating)
df_books.iloc[:,0:3]

Nombre  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                        Autor  Rating  
0                    JJ Smith     4.7  
1                Stephen King     4.6  
2          Jordan B. Peterson     4.7  
3               George Orwell     4.7  
4    National Geographic Kids     4.8  
..                        ...     ...  
545               Jeff Kinney     4.9  
546               Jen Sincero     4.7  
547               Jen Sincero     4.7  
548               Jen Sincero     4.7  
549               Jen Sincero     4.7  

[550 rows x 3 columns]

In [36]:
#Es posible filtrar lo que queremos mostrar

df_books.iloc[:6,2:]

Rating  Reviews  Precio  Anio       Genero
0     4.7    17350       8  2016  Non Fiction
1     4.6     2052      22  2011      Fiction
2     4.7    18979      15  2018  Non Fiction
3     4.7    21424       6  2017      Fiction
4     4.8     7665      12  2019  Non Fiction
5     4.4    12643      11  2011      Fiction

## Agregar o quitar datos con Pandas

In [13]:
df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0) 

In [4]:
#para mostrar las primeras 5 filas
df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [8]:
# Drop columns
#Borrar columnas

#el axis es 1 porque axis 0 son filas y axis 1 son columnas
df_books.drop('Genre', axis = 1).head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [14]:
#Pero esto no lo elimina de nuestro Dataframe real
#Drop solo lo borra de la salida, para borrarlo directamente

#Utilizando inplace = True
df_books.drop('Genre',axis=1,inplace=True)
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [15]:
#Otra forma
df_books = df_books.drop('Year',axis=1)
df_books.head(2)

Name        Author  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [16]:
#Utilizando algo propiamente de Python

del df_books['Price']
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

In [17]:
#Para borrar columnas

df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0) 

In [18]:
#Borramos el índice 0 del axis 0 (filas)
df_books.drop(0,axis=0).head(2)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  Price  Year        Genre  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction

In [19]:
#Otra forma de borrar múltiples filas

df_books.drop(range(0,10),axis=0).head(2)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  Price  Year        Genre  
10          4.6    23848      8  2017      Fiction  
11          4.6      460      2  2010  Non Fiction

In [20]:
#Agregar columnas
df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0) 


In [21]:
df_books['Nueva Columna'] = np.nan
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva Columna  
0              NaN  
1              NaN  
2              NaN  
3              NaN  
4              NaN  
..             ...  
545            NaN  
546            NaN  
547            NaN  
548            NaN  
549            NaN  

[550 rows x 8 columns]

In [22]:
df_books.shape[0]

550

In [23]:
data = np.arange(0,df_books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [24]:
df_books['Rango'] = data


In [26]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva Columna  Rango  
0              NaN      0  
1              NaN      1  
2              NaN      2  
3              NaN      3  
4              NaN      4  
..             ...    ...  
545            NaN    545  
546            NaN    546  
547            NaN    547  
548            NaN    548  
549            NaN    549  

[550 rows x 9 columns]

In [29]:
#Agregar filas utilizando append

df_books.append({'Name':'Cien años de Soledad', 
           'Author':'Gabriel García Márquez', 
           "User Rating": 4.8, 
           'Reviews':20000,
           'Year':1967, 
           'Price':25}, 
          ignore_index = True)

/tmp/ipykernel_6250/3017901947.py:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append({'Name':'Cien años de Soledad',


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
550                               Cien años de Soledad   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
550    Gabriel García Márquez          4.8    20000     25  1967          NaN   

     Nueva Columna  Rango  
0              NaN    0.0  
1              NaN    1.0  
2              NaN    2.0  
3              NaN    3.0  
4              NaN    4.0  
..             ...    ...  
546            NaN  546.0  
547            NaN  547.0  
548            NaN  548.0  
549            NaN  549.0  
550            NaN    NaN  

[551 rows x 9 columns]

In [30]:
is_bad = np.array(df_books['User Rating']) < 4.5
df_books['Is Bad'] = is_bad

In [31]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Nueva Columna  Rango  Is Bad  
0              NaN      0   False  
1              NaN      1   False  
2              NaN      2   False  
3              NaN      3   False  
4              NaN      4   False  
..             ...    ...     ...  
545            NaN    545   False  
546            NaN    546   False  
547            NaN    547   False  
548            NaN    548   False  
549            NaN    549   False  

[550 rows x 10 columns]

## Manejo de datos Nulos

In [32]:
my_dic = {
    'Col1': [1,2,3,np.nan],
    'Col2': [4,np.nan,6,7],
    'Col3': ['a','b','b',None]
}

df = pd.DataFrame(my_dic)
df

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   NaN     b
2   3.0   6.0     b
3   NaN   7.0  None

In [33]:
#Para saber si es nulo
df.isnull()

Col1   Col2   Col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [34]:
#Para metodos numéricos

df.isnull()*1

Col1  Col2  Col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [35]:
#Para llenar los valores nulos

df.fillna('Missing')

Col1     Col2     Col3
0      1.0      4.0        a
1      2.0  Missing        b
2      3.0      6.0        b
3  Missing      7.0  Missing

In [37]:
# Tambien puede llenarse con media
df.fillna(df.mean())

/tmp/ipykernel_6250/3092808955.py:2: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  df.fillna(df.mean())


Col1      Col2  Col3
0   1.0  4.000000     a
1   2.0  5.666667     b
2   3.0  6.000000     b
3   2.0  7.000000  None

In [38]:
#Otro modo

df.interpolate()

Col1  Col2  Col3
0   1.0   4.0     a
1   2.0   5.0     b
2   3.0   6.0     b
3   3.0   7.0  None

In [39]:
#Borrar los valores nulos

df.dropna()

Col1  Col2 Col3
0   1.0   4.0    a
2   3.0   6.0    b

In [42]:
df.dropna(subset = ['Col1'])

Col1  Col2 Col3
0   1.0   4.0    a
1   2.0   NaN    b
2   3.0   6.0    b

## Filtrado por condiciones

In [44]:
df_books = pd.read_csv('/home/jeffersonrl/Descargas/example.csv', sep = ',', header = 0) 

In [46]:
mayor_a_2016 = df_books['Year'] > 2016


In [47]:
#Para evaluar cuales libros son mayores a 2016
df_books[mayor_a_2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [48]:
#Sin usar variables

df_books[(df_books['Year'] > 2016) & (df_books['Genre']=='Fiction')]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [51]:
#Como filtrar por palabras

df_books[df_books['Author'].str.contains('Martin')]

Name                 Author  \
5        A Dance with Dragons (A Song of Ice and Fire)    George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...    George R. R. Martin   
40            Brown Bear, Brown Bear, What Do You See?        Bill Martin Jr.   
41            Brown Bear, Brown Bear, What Do You See?        Bill Martin Jr.   
118  Game of Thrones Boxed Set: A Game of Thrones/A...     George R.R. Martin   
119  Game of Thrones Boxed Set: A Game of Thrones/A...     George R.R. Martin   
120  Game of Thrones Boxed Set: A Game of Thrones/A...     George R.R. Martin   
486                   The Wonderful Things You Will Be  Emily Winfield Martin   
487                   The Wonderful Things You Will Be  Emily Winfield Martin   
488                   The Wonderful Things You Will Be  Emily Winfield Martin   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   

     User Rating  Reviews  Price  Year    Genre  
5            4.4    12643     11  2011  Fiction  
6            4.7    19735     30  2014  Fiction  
40           4.9    14344      5  2017  Fiction  
41           4.9    14344      5  2019  Fiction  
118          4.6     5594      5  2011  Fiction  
119          4.6     5594      5  2012  Fiction  
120          4.6     5594      5  2013  Fiction  
486          4.9     8842     10  2016  Fiction  
487          4.9     8842     10  2017  Fiction  
488          4.9     8842     10  2018  Fiction  
489          4.9     8842     10  2019  Fiction

In [52]:
#Si se desea hacer un filtrado negando una condición que ya tenemos

df_books[~mayor_a_2016]

Name               Author  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
0            4.7    17350      8  2016  Non Fiction  
1            4.6     2052     22  2011      Fiction  
5            4.4    12643     11  2011      Fiction  
6            4.7    19735     30  2014      Fiction  
9            4.6    23848      8  2016      Fiction  
..           ...      ...    ...   ...          ...  
540          4.8    21625      9  2013      Fiction  
541          4.8    21625      9  2014      Fiction  
542          4.8    21625      9  2015      Fiction  
543          4.8    21625      9  2016      Fiction  
546          4.7    14331      8  2016  Non Fiction  

[400 rows x 7 columns]

## Funciones principales de Pandas

In [53]:
#Función head trae los primeros registros

df_books.head()

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [54]:
#Con info da la información del dataframe

df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


In [55]:
#Para dar información estadisticos de los datos numéricos

df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [56]:
#Muestra los últimos 5 registros
df_books.tail()

Name       Author  \
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)  Jeff Kinney   
546  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
547  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
545          4.9     9413      8  2019      Fiction  
546          4.7    14331      8  2016  Non Fiction  
547          4.7    14331      8  2017  Non Fiction  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [58]:
#Cuanta memoria ocupa
df_books.memory_usage(deep=True)

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

In [60]:
#Para encontrar cuandos registros hay de cada autor

df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

In [61]:
#modificar

df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [62]:
df_books = df_books.append(df_books.iloc[0])

/tmp/ipykernel_6250/3653130519.py:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books = df_books.append(df_books.iloc[0])


In [63]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

In [65]:
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [66]:
df_books.drop_duplicates(keep = 'last') #Para que deje el ultimo

Name  \
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5         George R. R. Martin          4.4    12643     11  2011      Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[550 rows x 7 columns]

In [69]:
df_books.sort_values('Year', ascending=True)

Name            Author  \
513               Twilight (The Twilight Saga, Book 1)   Stephenie Meyer   
418  The Last Olympian (Percy Jackson and the Olymp...      Rick Riordan   
177                                      I, Alex Cross   James Patterson   
417                                   The Last Lecture      Randy Pausch   
331  The 7 Habits of Highly Effective People: Power...  Stephen R. Covey   
..                                                 ...               ...   
239  National Geographic Kids Why?: Over 1,111 Answ...     Crispin Boyer   
74   Difficult Riddles For Smart Kids: 300 Difficul...     M Prefontaine   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)   Naomi Kleinberg   
466  The Subtle Art of Not Giving a F*ck: A Counter...       Mark Manson   
356  The Complete Ketogenic Diet for Beginners: You...         Amy Ramos   

     User Rating  Reviews  Price  Year        Genre  
513          4.7    11676      9  2009      Fiction  
418          4.8     4628      7  2009      Fiction  
177          4.6     1320      7  2009      Fiction  
417          4.7     4028      9  2009  Non Fiction  
331          4.6     9325     24  2009  Non Fiction  
..           ...      ...    ...   ...          ...  
239          4.8     5347     16  2019  Non Fiction  
74           4.6     7955      5  2019  Non Fiction  
263          4.7    10820      5  2019  Non Fiction  
466          4.6    26490     15  2019  Non Fiction  
356          4.3    13061      6  2019  Non Fiction  

[551 rows x 7 columns]

## Group by

In [74]:
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [75]:
df_books.groupby('Author').sum().loc['William Davis']

User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [76]:
df_books.groupby('Author').sum().reset_index()

Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [78]:
df_books.groupby('Author').agg(['min','max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [80]:
df_books.groupby('Author').agg({'Reviews':['min','max'], 'User Rating': 'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [81]:
df_books.groupby(['Author','Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

## Merge, Join y Concat

In [82]:
df1 = pd.DataFrame({'A':['A0', 'A1', 'A2','A3'],
        'B':['B0', 'B1', 'B2','B3'],
	'C':['C0', 'C1', 'C2','C3'],
	'D':['D0', 'D1', 'D2','D3']})


df2 = pd.DataFrame({'A':['A4', 'A5', 'A6','A7'],
	'B':['B4', 'B5', 'B6','B7'],
	'C':['C4', 'C5', 'C6','C7'],
	'D':['D4', 'D5', 'D6','D7']})

In [84]:
pd.concat([df1,df2], ignore_index = True)

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [85]:
pd.concat([df1,df2],axis=1, ignore_index = True)

0   1   2   3   4   5   6   7
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7  B7  C7  D7

In [86]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [88]:
#Merge de izquierda y derecha

izq.merge(der, on = 'key')

key   A   B   C   D
0  k0  A0  B0  C0  D0
1  k1  A1  B1  C1  D1
2  k2  A2  B2  C2  D2
3  k3  A3  B3  C3  D3

In [89]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key2' : ['k0', 'k1', 'k2','k3'],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [92]:
izq.merge(der, left_on = 'key', right_on = 'key2')

key   A   B key2   C   D
0  k0  A0  B0   k0  C0  D0
1  k1  A1  B1   k1  C1  D1
2  k2  A2  B2   k2  C2  D2
3  k3  A3  B3   k3  C3  D3

In [93]:
izq = pd.DataFrame({'key' : ['k0', 'k1', 'k2','k3'],
 'A' : ['A0', 'A1', 'A2','A3'],
'B': ['B0', 'B1', 'B2','B3']})

der = pd.DataFrame({'key2' : ['k0', 'k1', 'k2',np.nan],
 'C' : ['C0', 'C1', 'C2','C3'],
'D': ['D0', 'D1', 'D2','D3']})

In [94]:
der

key2   C   D
0   k0  C0  D0
1   k1  C1  D1
2   k2  C2  D2
3  NaN  C3  D3

In [123]:
np.linspace(0,10,100)

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [95]:
izq.merge(der, left_on='key',right_on='key2')

key   A   B key2   C   D
0  k0  A0  B0   k0  C0  D0
1  k1  A1  B1   k1  C1  D1
2  k2  A2  B2   k2  C2  D2

In [97]:
#Con how decimos si es left join o right join
izq.merge(der, left_on='key',right_on='key2', how='left')

key   A   B key2    C    D
0  k0  A0  B0   k0   C0   D0
1  k1  A1  B1   k1   C1   D1
2  k2  A2  B2   k2   C2   D2
3  k3  A3  B3  NaN  NaN  NaN

In [98]:
izq.merge(der, left_on='key',right_on='key2', how='right')

key    A    B key2   C   D
0   k0   A0   B0   k0  C0  D0
1   k1   A1   B1   k1  C1  D1
2   k2   A2   B2   k2  C2  D2
3  NaN  NaN  NaN  NaN  C3  D3

In [99]:
izq = pd.DataFrame({'A': ['A0','A1','A2'],
  'B':['B0','B1','B2']},
  index=['k0','k1','k2'])

der =pd.DataFrame({'C': ['C0','C1','C2'],
  'D':['D0','D1','D2']},
  index=['k0','k2','k3']) 

In [101]:
#Comando join - Index Match

print(izq)
print(der)

     A   B
k0  A0  B0
k1  A1  B1
k2  A2  B2
     C   D
k0  C0  D0
k2  C1  D1
k3  C2  D2


In [102]:
izq.join(der)

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [103]:
izq.join(der, how = 'left')

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

## Pivot_table y melt

In [104]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

In [105]:
#aplicando pivot_table:

df_books.pivot_table(index='Author', columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [106]:
#Melt

df_books[['Name','Genre']].head()

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [ ]:
arr1 = np.array([7,8],[2,1],[2,4])
arr1.

In [107]:
df_books[['Name','Genre']].head().melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [108]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction
550  2016    Genre  Non Fiction

[551 rows x 3 columns]

## Apply

In [110]:
def two_times(value):
    return value * 2

In [111]:
df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
546    9.4
547    9.4
548    9.4
549    9.4
0      9.4
Name: User Rating, Length: 551, dtype: float64

In [114]:
df_books['Rating_2'] = df_books['User Rating'].apply(lambda x: x*3)

In [116]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0        14.1  
1        13.8  
2        14.1  
3        14.1  
4        14.4  
..        ...  
546      14.1  
547      14.1  
548      14.1  
549      14.1  
0        14.1  

[551 rows x 8 columns]

In [119]:
df_books['Rating_2']=df_books.apply(lambda x: x['User Rating']*3 if x['Genre'] == 'Fiction' else x['User Rating'], axis = 1)

In [120]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   

     Rating_2  
0         4.7  
1        13.8  
2         4.7  
3        14.1  
4         4.8  
..        ...  
546       4.7  
547       4.7  
548       4.7  
549       4.7  
0         4.7  

[551 rows x 8 columns]

In [122]:
arr = np.array([13, 6, 3, 5, 10])
np.sort(arr)

array([ 3,  5,  6, 10, 13])

In [126]:
arr = np.array([13, 6, 3, 5, 10])
np.argmax(arr)

0

In [128]:
arr[arr>7]

array([13, 10])

In [129]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])